/*
Copyright 2016 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package v1beta1

// This file contains a collection of methods that can be used from go-restful to
// generate Swagger API documentation for its models. Please read this PR for more
// information on the implementation: https://github.com/emicklei/go-restful/pull/215
//
// TODOs are ignored from the parser (e.g. TODO(andronat):... || TODO:...) if and only if
// they are on one line! For multiple line or blocks that you want to ignore use ---.
// Any context after a --- is ignored.
//
// Those methods can be generated by using hack/update-generated-swagger-docs.sh

// AUTO-GENERATED FUNCTIONS START HERE
var map_Event = map[string]string{
	"":                "Event is a report of an event somewhere in the cluster. It generally denotes some state change in the system.",
	"eventTime":       "Required. Time when this Event was first observed.",
	"series":          "Optional. Data about the Event series this event represents or nil if it's a singleton Event.",
	"eventSource":     "Required. Kubernetes component that generated the Event.",
	"action":          "Required. What Origin did/failed to do.",
	"object":          "Optional. On what Origin acted upon.",
	"secondaryObject": "Optional secondary Object for more complex actions.",
	"severity":        "Required. Severity of the Event.",
	"message":         "Optional. A human-readable description of the status of this operation.",
}

func (Event) SwaggerDoc() map[string]string {
	return map_Event
}

var map_EventAction = map[string]string{
	"": "Information about action that was taken",
}

func (EventAction) SwaggerDoc() map[string]string {
	return map_EventAction
}

var map_EventList = map[string]string{
	"":         "EventList is a list of Event objects.",
	"metadata": "Standard list metadata. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#metadata",
	"items":    "Items is a list of schema objects.",
}

func (EventList) SwaggerDoc() map[string]string {
	return map_EventList
}

var map_EventSeries = map[string]string{
	"uid":              "Unique identifier of the Event series.",
	"count":            "Number of Events in this series until last heartbeat.",
	"lastObservedTime": "Time when last Event from the series was seen before last heartbeat.",
	"lastHeartbeat":    "Last time when seried data was updated.",
	"state":            "Information whether this series is ongoing or finished.",
}

func (EventSeries) SwaggerDoc() map[string]string {
	return map_EventSeries
}

var map_EventSource = map[string]string{
	"":          "Information about component that emits Event",
	"component": "Component from which the event is generated.",
	"id":        "String that identifies the component emitting the Event",
}

func (EventSource) SwaggerDoc() map[string]string {
	return map_EventSource
}

// AUTO-GENERATED FUNCTIONS END HERE
