/*
Copyright 2017 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// This file was automatically generated by informer-gen

package v1alpha1

import (
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
	example_v1alpha1 "k8s.io/sample-controller/pkg/apis/example/v1alpha1"
	versioned "k8s.io/sample-controller/pkg/client/clientset/versioned"
	internalinterfaces "k8s.io/sample-controller/pkg/client/informers/externalversions/internalinterfaces"
	v1alpha1 "k8s.io/sample-controller/pkg/client/listers/example/v1alpha1"
	time "time"
)

// NGINXInformer provides access to a shared informer and lister for
// NGINXs.
type NGINXInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.NGINXLister
}

type nGINXInformer struct {
	factory internalinterfaces.SharedInformerFactory
}

// NewNGINXInformer constructs a new informer for NGINX type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewNGINXInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				return client.ExampleV1alpha1().NGINXs(namespace).List(options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				return client.ExampleV1alpha1().NGINXs(namespace).Watch(options)
			},
		},
		&example_v1alpha1.NGINX{},
		resyncPeriod,
		indexers,
	)
}

func defaultNGINXInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewNGINXInformer(client, v1.NamespaceAll, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc})
}

func (f *nGINXInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&example_v1alpha1.NGINX{}, defaultNGINXInformer)
}

func (f *nGINXInformer) Lister() v1alpha1.NGINXLister {
	return v1alpha1.NewNGINXLister(f.Informer().GetIndexer())
}
