apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: system:podsecuritypolicy:persistent-volume-binder
  namespace: default
  labels:
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: Reconcile
rules:
- apiGroups:
  - extensions
  resourceNames:
  - system.persistent-volume-binder
  resources:
  - podsecuritypolicies
  verbs:
  - use
