apiVersion: extensions/v1beta1
kind: PodSecurityPolicy
metadata:
  name: unprivileged
  annotations:
    kubernetes.io/description: 'unprivileged allows full access to all pod
      settings except those that grant host privileges.'
    seccomp.security.alpha.kubernetes.io/allowedProfileNames: '*'
  labels:
    kubernetes.io/cluster-service: 'true'
    addonmanager.kubernetes.io/mode: Reconcile
spec:
  privileged: false
  allowPrivilegeEscalation: true
  volumes: # All volume types except HostPath
  - 'emptyDir'
  - 'gcePersistentDisk'
  - 'awsElasticBlockStore'
  - 'gitRepo'
  - 'secret'
  - 'nfs'
  - 'iscsi'
  - 'glusterfs'
  - 'persistentVolumeClaim'
  - 'rbd'
  - 'quobyte'
  - 'flexVolume'
  - 'cinder'
  - 'cephFS'
  - 'flocker'
  - 'downwardAPI'
  - 'fc'
  - 'azureFile'
  - 'configMap'
  - 'vsphereVolume'
  - 'azureDisk'
  - 'photonPersistentDisk'
  - 'projected'
  - 'portworxVolume'
  - 'scaleIO'
  - 'storageos'
  hostNetwork: false
  hostIPC: false
  hostPID: false
  runAsUser:
    rule: 'RunAsAny'
  seLinux:
    rule: 'RunAsAny'
  supplementalGroups:
    rule: 'RunAsAny'
  fsGroup:
    rule: 'RunAsAny'
  readOnlyRootFilesystem: false
