apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  labels:
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: Reconcile
  name: podsecuritypolicy:unprivileged
rules:
- apiGroups:
  - extensions
  resourceNames:
  - unprivileged
  resources:
  - podsecuritypolicies
  verbs:
  - use
